version: '3.1'

services:
  postgres:
    image: postgres:15
    ports:
      - "${DOCKER_POSTGRES_PORT_FORWARD-5432}:5432"
    volumes:
      - ${PGDATA-./.data/db}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-postgres}"
      POSTGRES_DB: "${POSTGRES_DB-postgres}"

  django:
    stdin_open: true
    tty: true
    build: .
    command: /app/docker-init.sh
    volumes:
      - ./:/app
    ports:
      - "${DOCKER_DJANGO_PORT_FORWARD-8000}:8000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      POSTGRES_USER: "${POSTGRES_USER-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-postgres}"
      POSTGRES_DB: "${POSTGRES_DB-postgres}"
      POSTGRES_HOST: "${POSTGRES_HOST-postgres}"
      POSTGRES_PORT: "${POSTGRES_PORT-5432}"
